### ISSUE TITLE
QV Assessment idea

### ISSUE THREAD

**Issue by sivico26** [rrwick/Polypolish-paper#1]
Hi, I posted this comment a few days ago in Bioarxiv but apparently is still pending approval ... Anyway, I am putting it here so you can see it.
***
Hi, exciting development! As I was reading the paper and the main point of Polypolish is to reduce errors in repetitive regions, I was almost sure that [Merqury](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02134-9) was going to be used to assess the error reduction. Have you heard about it before?

I have not heard of ALE before, but by your description, it seems a mapping-based score, which would skew to non-repeats. I think Merqury might be a better fit because it is kmer-based, and thus it does not suffer from the mapping bias. Among other things, Merqury can provide a global QV score for your assembly, comparing the assembly kmer spectra to the short-reads kmer spectra. I suspect Merqury's QV scores can better reflect the reduction in repeat regions.

Furthermore, I wonder what one can achieve if you use both metrics. Being ALE a good representative of non-repetitive error reduction and Merqury's QVs of the global error reduction, one might think that something like the ratio or the difference of both could directly correlate to error reduction in repetitive regions. Although one would have to think about how to normalize the metrics to make them comparable, I think it is still an idea worth exploring.

I hope this comment helps and I wish you the best.

Regards,

Sivico

**Comment by rrwick** [comment]
Thanks - I hadn't noticed the comment on bioRxiv until I read this. Just responded there, but I'll follow your lead and copy it here as well.

---

Hi Sivico,

I haven't tried Merqury, so thanks for that recommendation! I will definitely check it out in the future.

That being said, I think ALE should work in repeat regions, in a way. It uses a number of different metrics, one of which is k-mer-based. And it uses the evenness of read depth as well, so errors in repeats that cause alignments to skew to error-free instances of the repeat will cause uneven depth and therefore a worse ALE score.

But Merqury sounds good too, and I like your idea of using both. Lots of stuff to try in the future!

Ryan
